2301C2TempEmbedding/Models/Item.cs
using System;
using System.Collections.Generic;

namespace _2301C2TempEmbedding.Models;

public partial class Item
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Description { get; set; } = null!;

    public int Price { get; set; }

    public string Image { get; set; } = null!;

    public int? CatId { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual Category? Cat { get; set; }
}

2301C2TempEmbedding/Controllers/ItemController.cs
using _2301C2TempEmbedding.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace _2301C2TempEmbedding.Controllers
{
    public class ItemController : Controller
    {
        //EcommerceContext db = new EcommerceContext();
        private readonly EcommerceContext db;
        public ItemController(EcommerceContext _db)
        {
            db = _db;
        }

        public IActionResult Index()
        {
            var ItemsData = db.Items.Include(a => a.Cat);
            return View(ItemsData);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.CatId = new SelectList(db.Categories, "CatId", "CatName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item item, IFormFile file)
        {
            var imageName = DateTime.Now.ToString("yymmddhhmmss");//8489327234846347
            imageName += Path.GetFileName(file.FileName);//8489327234846347apple.jpg
            string imagepath= Path.Combine(HttpContext.Request.PathBase.Value,"wwwroot/Uploads");
            var imagevalue = Path.Combine(imagepath,imageName);
            using(var stream = new FileStream(imagevalue, FileMode.Create))
            {
                file.CopyTo(stream);
            }
            string dbimage = Path.Combine("/Uploads", imageName);// /Uploads/8489327234846347apple.jpg
            item.Image = dbimage;

            db.Items.Add(item);
            db.SaveChanges();
            ViewBag.CatId = new SelectList(db.Categories, "CatId", "CatName");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var item1 = db.Items.Find(id);
            ViewBag.CatId = new SelectList(db.Categories, "CatId", "CatName");
            return View(item1);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Item item, IFormFile file, string oldimage)
        {
            var dbimage = "";
            if (file != null && file.Length > 0)
            {

                var imageName = DateTime.Now.ToString("yymmddhhmmss");//8489327234846347
                imageName += Path.GetFileName(file.FileName);//8489327234846347apple.jpg
                string imagepath = Path.Combine(HttpContext.Request.PathBase.Value, "wwwroot/Uploads");
                var imagevalue = Path.Combine(imagepath, imageName);
                using (var stream = new FileStream(imagevalue, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
                dbimage = Path.Combine("/Uploads", imageName);// /Uploads/8489327234846347apple.jpg
                item.Image = dbimage;

                db.Items.Update(item);
                db.SaveChanges();
              
            }
            else
            {
                item.Image = oldimage;

                db.Items.Update(item);
                db.SaveChanges();
               
            }
            ViewBag.CatId = new SelectList(db.Categories, "CatId", "CatName");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var item1 = db.Items.Find(id);
            ViewBag.CatId = new SelectList(db.Categories, "CatId", "CatName");
            if(item1 != null)
            {

            return View(item1);
            }
            else
            {
                return RedirectToAction("Index");

            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Item item)
        {
            

                db.Items.Remove(item);
                db.SaveChanges();

            ViewBag.CatId = new SelectList(db.Categories, "CatId", "CatName");
            return RedirectToAction("Index");
        }



    }
}

2301C2TempEmbedding/Views/Item/Create.cshtml
@model _2301C2TempEmbedding.Models.Item

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" asp-controller="Item" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" name="file" asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatId" class="control-label"></label>
                <select asp-for="CatId" class ="form-control" asp-items="ViewBag.CatId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

2301C2TempEmbedding/Views/Item/Delete.cshtml
@model _2301C2TempEmbedding.Models.Item

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Html.DisplayFor(model => model.Image)" class="rounded-circle" height="60" width="60">
            
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.CatId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

2301C2TempEmbedding/Views/Item/Edit.cshtml
@model _2301C2TempEmbedding.Models.Item

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" name="oldimage" value="@Model.Image" />
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" name="file" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatId" class="control-label"></label>
                <select asp-for="CatId" class="form-control" asp-items="ViewBag.CatId"></select>
                <span asp-validation-for="CatId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

2301C2TempEmbedding/Views/Item/Index.cshtml
@model IEnumerable<_2301C2TempEmbedding.Models.Item>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
               Category Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                    <img src="@Html.DisplayFor(modelItem => item.Image)" class="rounded-circle" height="60" width="60">
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cat.CatName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>